---
- name: Dell OS10 
  hosts: all
  collections: 
    - dellemc.os10
  tasks:
    - name: Ping
      dellos10_command:
        commands:
          - show processes cpu summary
      register: result

    - name: Output
      debug: var=result.stdout_lines

