---
- name: Dell OS10 
  hosts: 10.3.3.18
  gather_facts: false
  collections:
    - dellemc.os10
  tasks:
    - name: Description Update Dell OS10
      os10_command:
        commands:
          - show version
