---
- name: Dell OS10 
  hosts: Test
  collections:
    - dellemc.os10
  tasks:
    - name: Port description Update Dell OS10
      dellos10_config:
        commands:
          - interface ethernet 1/1/31
          - description <<LTPOWM03U29NXPOCN1_19.21_A_P1>>
          - exit
          - interface ethernet 1/1/32
          - description <<LTPOWM03U29NXPOCN2_19.22_B_P1>>
          - exit
          - interface ethernet 1/1/33
          - description <<LTPOWM03U29NXPOCN3_19.23_C_P1>>
          - exit
          - interface ethernet 1/1/34
          - description <<LTPOWM03U29NXPOCN4_19.24_D_P1>>
          - exit
          - interface ethernet 1/1/35
          - description <<LTPOWM03U29NXPOCN1_19.21_A_P3>>
          - exit
          - interface ethernet 1/1/36
          - description <<LTPOWM03U29NXPOCN2_19.22_B_P3>>
          - exit
          - interface ethernet 1/1/37
          - description <<LTPOWM03U29NXPOCN3_19.23_C_P3>>
          - exit
          - interface ethernet 1/1/38
          - description <<LTPOWM03U29NXPOCN4_19.24_D_P3>>
          - exit
          - write memory
