---
- name: Dell OS10 
  hosts: test
  gather_facts: false
  collections:
    - dellemc.os10
  tasks:
    - name: Description Update Dell OS10
      os10_command:
        commands:
          - show version
          - show interface
        wait_for:
          - result[0] contains OS10
          - result[1] contains Ethernet
